--CONJUNTOS--
select e.EMPLOYEE_ID, e.JOB_ID, HIRE_DATE, SALARY from EMPLOYEES e
where DEPARTMENT_ID in (60,90,100)
UNION
select em.EMPLOYEE_ID, JOB_ID, HIRE_DATE, SALARY from EMPLOYEES em where  JOB_ID = 'IT_PROG' ORDER BY SALARY;

select e.EMPLOYEE_ID, e.JOB_ID, HIRE_DATE, SALARY from EMPLOYEES e
where DEPARTMENT_ID in (60,90,100)
UNION ALL
select em.EMPLOYEE_ID, JOB_ID, HIRE_DATE, SALARY from EMPLOYEES em where  JOB_ID = 'IT_PROG' ORDER BY SALARY;

select e.EMPLOYEE_ID, e.JOB_ID, HIRE_DATE, SALARY from EMPLOYEES e
where DEPARTMENT_ID in (60,90,100)
intersect
select em.EMPLOYEE_ID, JOB_ID, HIRE_DATE, SALARY from EMPLOYEES em where  JOB_ID = 'IT_PROG' ORDER BY SALARY;


select e.EMPLOYEE_ID, e.JOB_ID, HIRE_DATE, SALARY from EMPLOYEES e
where DEPARTMENT_ID in (60,90,100)
minus
select em.EMPLOYEE_ID, JOB_ID, HIRE_DATE, SALARY from EMPLOYEES em where  JOB_ID = 'IT_PROG' ORDER BY SALARY;