select e.EMPLOYEE_ID, j.JOB_TITLE, d.DEPARTMENT_NAME, l.CITY, l.STATE_PROVINCE from EMPLOYEES e
    JOIN JOBS j on (e.JOB_ID = j.JOB_ID)
    JOIN DEPARTMENTS d on (e.DEPARTMENT_ID = d.DEPARTMENT_ID)
    join LOCATIONS l on (l.LOCATION_ID = d.LOCATION_ID)
order by e.EMPLOYEE_ID;


select EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, EMPLOYEES.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME
from EMPLOYEES join DEPARTMENTS on EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

